-- MySQL Script generated by MySQL Workbench
-- Fri Jul 24 17:21:36 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `chat` ;

-- -----------------------------------------------------
-- Table `chat`.`roomname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`roomname` (
  `idroomname` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idroomname`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`username`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`username` (
  `idusername` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `roomname_idroomname` INT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`idusername`, `roomname_idroomname`)  COMMENT '',
  INDEX `fk_username_roomname1_idx` (`roomname_idroomname` ASC)  COMMENT '',
  CONSTRAINT `fk_username_roomname1`
    FOREIGN KEY (`roomname_idroomname`)
    REFERENCES `chat`.`roomname` (`idroomname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`messages` (
  `idmessages` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `text` VARCHAR(45) NOT NULL COMMENT '',
  `username_idusername` INT NOT NULL COMMENT '',
  `username_roomname_idroomname` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idmessages`, `username_idusername`, `username_roomname_idroomname`)  COMMENT '',
  INDEX `fk_messages_username1_idx` (`username_idusername` ASC, `username_roomname_idroomname` ASC)  COMMENT '',
  CONSTRAINT `fk_messages_username1`
    FOREIGN KEY (`username_idusername` , `username_roomname_idroomname`)
    REFERENCES `chat`.`username` (`idusername` , `roomname_idroomname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
